name: Development build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Development build

    runs-on: macos-latest

    steps:
      - name: Install dependencies
        run: |
          brew install temurin@8 ldid make

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive

      - name: Checkout repository submodules
        env:
          GIT_LFS_SKIP_SMUDGE: 1
        run: |
          git lfs install --skip-smudge
          git config --global filter.lfs.smudge "git-lfs smudge --skip -- %f"
          git config --global filter.lfs.process "git-lfs filter-process --skip"

          git submodule sync --recursive
          git submodule update --init --recursive
          
      - name: Build
        run: |
          export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH
          export SLIMMED=1
          # Pass the flag to glslang to bypass the missing SPIR-V tools check
          export ENABLE_OPT=0

          gmake -j$(sysctl -n hw.ncpu) package
          gmake -j$(sysctl -n hw.ncpu) package TROLLSTORE_JIT_ENT=1

      - name: Upload regular ipa
        uses: actions/upload-artifact@v4
        with:
          name: Amethyst.ipa
          path: artifacts/org.angelauramc.amethyst-*.ipa

      - name: Upload TrollStore tipa
        uses: actions/upload-artifact@v4
        with:
          name: Amethyst-TrollStore.tipa
          path: artifacts/org.angelauramc.amethyst-*-trollstore.tipa

      - name: Upload jre
        uses: actions/upload-artifact@v4
        with:
          name: java_runtimes
          path: artifacts/java_runtimes/*
